# file: postgresql/tasks/install.yml

# The standard ca-certs are needed because  without them apt_key will fail to
# validate www.postgresql.org (or probably any other source).
- name: PostgreSQL | Make sure the CA certificates are available
  apt:
    pkg: ca-certificates
    state: present

- name: PostgreSQL | Install acl for fix set permissions on the temporary files | apt
  apt:
    pkg: acl
    state: present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"

- name: PostgreSQL | Add PostgreSQL repository apt-key
  apt_key:
    id: "{{ postgresql_apt_key_id }}"
    url: "{{ postgresql_apt_key_url }}"
    state: present
  when: postgresql_apt_key_url and postgresql_apt_key_id

- name: PostgreSQL | Add PostgreSQL repository
  apt_repository:
    repo: "{{ postgresql_apt_repository }}"
    state: present
  when: postgresql_apt_repository | default('') != ''

- name: PostgreSQL | Add PostgreSQL repository preferences
  template:
    src: etc_apt_preferences.d_apt_postgresql_org_pub_repos_apt.pref.j2
    dest: /etc/apt/preferences.d/apt_postgresql_org_pub_repos_apt.pref
  when: postgresql_apt_pin_priority|bool|default(false)

- name: PostgreSQL | Make sure the dependencies are installed
  apt:
    pkg: "{{ postgresql_apt_dependencies }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"

- name: PostgreSQL | Test for PostgreSQL binary
  stat:
    path: /usr/bin/psql
  register: postgres_binary

- name: PostgreSQL | Install PostgreSQL
  apt:
    name:
      - "postgresql-{{postgresql_version}}{%if postgresql_patch_version%}={{postgresql_patch_version}}{%endif%}"
      - "postgresql-client-{{postgresql_version}}{%if postgresql_patch_version%}={{postgresql_patch_version}}{%endif%}"
      - "postgresql-contrib-{{postgresql_version}}{%if postgresql_patch_version%}={{postgresql_patch_version}}{%endif%}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  environment: "{{postgresql_env}}"
  when: postgres_binary.stat.exists == false

- name: PostgreSQL | PGTune
  apt:
    name: pgtune
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  environment: "{{postgresql_env}}"
  when: postgresql_pgtune
